name: gradlew_earlybird_feature_dev

on:   
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: clone EarlyBird
        run: git clone https://github.com/americanexpress/earlybird.git
      - name: install EarlyBird
        working-directory: ./earlybird/
        run: ./build.sh && sudo ./install.sh
      - name: EarlyBird launch
        working-directory: ./earlybird/
        run: sudo go-earlybird --path=$GITHUB_WORKSPACE
        continue-on-error: true
      - name: Tests results
        uses: actions/upload-artifact@v1
        with:
          name: earlybird_report
          path: ./earlybird/earlybird_report.txt
