name: gradlew_assemble_dev_to_master

on:   
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble with Gradle
        run: gradle assembleRelease
      - name: Set date variable
        run: CURR_DATE=$(date '+%Y-%m-%d-%H-%M')
      - uses: actions/upload-artifact@v1
        with:
          name: assembleRelease
          path: app/build/outputs/apk