name: gradlew_assemble_feature_to_dev

on:   
  pull_request:
    branches: [feature, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Give run perm to script
        run: chmod +x ./gradlew
      - name: Assemble with Gradle
        run: ./gradlew assembleDebug
      - name: Assemble with Gradle
        run: ls -la app/build
      - name: Set date variable
        run: CURR_DATE=$(date '+%Y-%m-%d-%H-%M')
      - name: Upload APK
        run: curl --upload-file app/build/outputs/apk/app-debug.apk https://transfer.sh/$CURR_DATE.apk