name: gradlew_depUpdate_feature_dev

on:   
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Dependencies
        run: gradle dependencyUpdates -Drevision=release > dep_update.txt
      - name: Tests results
        uses: actions/upload-artifact@v1
        with:
          name: dependency_updates_report
          path: ./dep_update.txt
